baseURL = "https://www.greenzero.us/"
languageCode = "en-us"
theme = "site-theme"
title = "Green Zero Development"
enableRobotsTXT = true

[[menu.mobile]]
    identifier = "Work on your website"
    name = "Work on your website"
    url = ""
    weight = 1
        [[menu.mobile]]
            identifier = "Speed up your website"
            name = "Speed up your website"
            url = "/speed-up-website/"
            weight = 1
            parent = "Work on your website"
        [[menu.mobile]]
            identifier = "Help with website security"
            name = "Help with website security"
            url = "/secure-website/"
            weight = 2
            parent = "Work on your website"
        [[menu.mobile]]
            identifier = "Improve editing tools"
            name = "Improve editing tools"
            url = "/better-editing-tools-for-website/"
            weight = 3
            parent = "Work on your website"
[[menu.mobile]]
    identifier = "Ask a question"
    name = "Ask a question"
    url = "/general-contact/"
    weight = 2
[[menu.mobile]]
    identifier = "Case Studies"
    name = "Case Studies"
    url = "/case-study/"
    weight = 3
[[menu.mobile]]
    identifier = "Get a website review"
    name = "Get a website review"
    url = "/free-site-review/"
    weight = 4
[params.tracking]
    cloudinary_url = ""
[params.publishing_settings]
    site_in_production = true

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "Algolia"]

[params.algolia]
    appId = ""
    search_key = ""
    index_name = ""

[params.extra_tools]
    algolia_search = false
    font_awesome = true
    floating_header = true

[markup.goldmark.renderer]
unsafe= true